### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Chaitanyagithubacc** [indranil180/VideoRAG#1]
Hi Indra

I am trying to use your code from your github account ,but facing more issues

I am suggesting as an optimistic guy to improve,
1.please add requirements.txt file
2.you are redirecting to hugging face-https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct/blob/main/README.md
again it is having multiple files but requirement.txt file missing

as per your requirement,I feel ,it doesnot  needed all files from huggingface account.Please be customised by using others account 

update it to make users more comfortable

**Comment by indranil180** [comment]
Hello @Chaitanyagithubacc ,

Apologies for the delayed response and the inconvenience caused while trying to run the code.

I’ve added a requirements.txt file to the repository. Please refer to it—I hope this helps you run the code successfully now :)
